<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div><a href="/specification/addSpecification">添加说明书</a></div>
<div><a href="/specification/allSpecification">所有说明书</a></div>
<div><a href="/specification/addSpecificationContent">添加说明书内容</a></div>
<div><a href="/specification/allSpecificationContent">所有说明书内容</a></div>
</body>
</html>