<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="" method="post">
    <label for=""><input type="hidden" name="id" value="<?php echo $data['id']; ?>"></label>
    <label for="">name:<input type="text" name="name" placeholder="<?php echo $data['specification_name']; ?>"></label>
    <label for="">sort:<input type="text" name="sort" placeholder="<?php echo $data['sort']; ?>"></label>
    <label for=""><input type="submit" value="修改"></label>
</form>
</body>
</html>